name: flutter_dynamic_render
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/simonkimi/flutter_dynamic_render

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
